CREATE TABLE payments (
  payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
  admin_id INTEGER DEFAULT 0,
  teacher_id INTEGER DEFAULT 0,
  amount INTEGER DEFAULT 0,
  date_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
